### ISSUE TITLE
작성된 ERD로 DB에 테이블을 생성한다

### ISSUE THREAD

**Issue by snowcrab382** [SWM-snowWhite/SeekTam#109]

**Comment by snowcrab382** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-649d4d45fe595c33f065f10d/issues/SWM-snowWhite/SeekTam/109?planning-poker) with Zenhub @snowcrab382 @JuHyeokParkk @Jureamer

**Comment by JuHyeokParkk** [comment]
![image](https://github.com/SWM-snowWhite/SeekTam/assets/77018024/b2936c4e-27d5-49e9-8dca-aa7ae92baace)
MySQL Workbench 환경에서 쿼리 실행 => 테이블 생성
(food 테이블은 임시 테이블)
