### ISSUE TITLE
샘플데이터를 주입하여 DB작동 테스트를 실시한다

### ISSUE THREAD

**Issue by snowcrab382** [SWM-snowWhite/SeekTam#110]

**Comment by snowcrab382** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-649d4d45fe595c33f065f10d/issues/SWM-snowWhite/SeekTam/110?planning-poker) with Zenhub @snowcrab382 @JuHyeokParkk @Jureamer

**Comment by JuHyeokParkk** [comment]
![image](https://github.com/SWM-snowWhite/SeekTam/assets/77018024/bf88d593-82dc-4668-a8f9-ba255518700a)
DB에 샘플 데이터 추가 후 RDS에 접근해 데이터를 가져오는 것을 테스트 코드를 통해 확인
