### ISSUE TITLE
IAM 권한을 설계한다

### ISSUE THREAD

**Issue by snowcrab382** [SWM-snowWhite/SeekTam#121]

**Comment by snowcrab382** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-649d4d45fe595c33f065f10d/issues/SWM-snowWhite/SeekTam/121?planning-poker) with Zenhub @snowcrab382 @JuHyeokParkk @Jureamer

**Comment by JuHyeokParkk** [comment]
![image](https://github.com/SWM-snowWhite/SeekTam/assets/77018024/56508194-3d9d-4cc5-b116-60ac86ec024e)

back, client, admin 용 IAM 생성 및 권한 추가 (보안상 root 계정 사용 지양)
