### ISSUE TITLE
스프링 프레임워크 기반 WAS/WS 환경을 구축한다

### ISSUE THREAD

**Issue by snowcrab382** [SWM-snowWhite/SeekTam#125]

**Comment by snowcrab382** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-649d4d45fe595c33f065f10d/issues/SWM-snowWhite/SeekTam/125?planning-poker) with Zenhub @snowcrab382 @JuHyeokParkk @Jureamer

**Comment by JuHyeokParkk** [comment]
![image](https://github.com/SWM-snowWhite/SeekTam/assets/77018024/37b32b77-7086-4bd7-82b5-d3a5c86f5acc)
=> EC2 환경에서 **RDS, Spring Boot(Tomcat) + Nginx 설정 이후 샘플 api 테스트 완료**(seektam.link 도메인 활용)

![image](https://github.com/SWM-snowWhite/SeekTam/assets/77018024/9179f582-1578-4c33-bb8c-2f074b762765)
=> **Nginx 연결 완료 시 초기 화면**

![image](https://github.com/SWM-snowWhite/SeekTam/assets/77018024/83c5a9de-ada3-4fe7-92da-b33bdc3b54c2)
=> **/etc/nginx/nginx.conf** 파일의 일부 내용. 우선 클라이언트의 모든 요청에 대해 바로 WAS로 연결되도록 설정함. 정적 컨텐츠에 대한 요청 또는 특정 url 요청에 대해서는 nginx에서 처리하도록 설정 가능(의논 필요), 리버스 프록시에 대한 내용 학습 필요할 듯
