### ISSUE TITLE
MySQL 환경을 구축한다

### ISSUE THREAD

**Issue by snowcrab382** [SWM-snowWhite/SeekTam#127]

**Comment by snowcrab382** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-649d4d45fe595c33f065f10d/issues/SWM-snowWhite/SeekTam/127?planning-poker) with Zenhub @snowcrab382 @JuHyeokParkk @Jureamer

**Comment by JuHyeokParkk** [comment]
![image](https://github.com/SWM-snowWhite/SeekTam/assets/77018024/031c0445-eb4e-4d57-9b12-32a4e8fcdc93)
RDS(MySQL) 생성
