### ISSUE TITLE
변경된 디자인의 와이어프레임을 작성한다

### ISSUE THREAD

**Issue by Muzzle-kr** [SWM-snowWhite/SeekTam#177]
- [x] 신규 와이어프레임 작성
- [x] 디자인 외주 검토 요청

**Comment by snowcrab382** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-649d4d45fe595c33f065f10d/issues/SWM-snowWhite/SeekTam/177?planning-poker) with Zenhub @snowcrab382 @JuHyeokParkk @Jureamer
